version: 1.0.{build}
os: Visual Studio 2015
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- cmd: appveyor DownloadFile https://go.microsoft.com/fwlink/?LinkID=809122
- cmd: DotNetCore.1.0.0-SDK.Preview2-x64.exe /quiet
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
before_build:
- dotnet restore
- npm i 
- node aspnetcore-version.js
build:
  verbosity: minimal
  publish_nuget: true
test_script:
  - cmd: dotnet test -c %CONFIGURATION% --no-build .\tests\TinyPng.Tests\
build_script:
 - dotnet pack -c %CONFIGURATION% --version-suffix %LABEL% -o .\artifacts .\src\TinyPNG\project.json
artifacts:
- path: artifacts\**\*.*
configuration: Release
deploy:
- provider: NuGet
  api_key:
    secure: Gerln5x/jQ3CsCjXe76zQuP2Rjh12sKBH2wj88LIpt1IQym1+6MlFVWmvx5j+KSw
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: release
cache:
- '%USERPROFILE%\.nuget\packages'    
- node_modules 
- %APPDATA%\npm-cache

     